############# Portuguese navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Serviços"
pageRef = "#services"
weight = 2

[[main]]
name = "Sobre Nós"
pageRef = "#about"
weight = 3

[[main]]
name = "Casos de Sucesso"
pageRef = "#cases"
weight = 4

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 5
